name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
     
          script: |
            mkdir test1
            cd test1
            touch tssssss.php
            git clone git@github.com:olehpitsun/cicdex.git
            echo 'Deployment successful to digitsal ocean1' 
